apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-staging
  template:
    metadata:
      labels:
        app: api-staging
    spec:
      containers:
        - name: api-staging
          image: irwan34/api-service:e4d69a4abd86cdf26684baf9fa8de4cf2e121c5a
          ports:
            - containerPort: 8080

