apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-staging
  template:
    metadata:
      labels:
        app: api-staging
    spec:
      containers:
        - name: api-staging
          image: irwan34/api-service:5056a0b328dc51b0ed5cfb02101d730021263eab
          ports:
            - containerPort: 8080

