apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-staging
  template:
    metadata:
      labels:
        app: api-staging
    spec:
      containers:
        - name: api-staging
          image: irwan34/api-service:f82520269d3532785c21b031f0c1905c47c8311c
          ports:
            - containerPort: 8080

