apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-staging
  template:
    metadata:
      labels:
        app: frontend-staging
    spec:
      containers:
        - name: frontend-staging
          image: irwan34/frontend-service:96a2376a62c60150fbc5c6cb60a6b976794e22f8
          ports:
            - containerPort: 8080

