apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-staging
  template:
    metadata:
      labels:
        app: frontend-staging
    spec:
      containers:
        - name: frontend-staging
          image: irwan34/frontend-service:f82520269d3532785c21b031f0c1905c47c8311c
          ports:
            - containerPort: 8080

