apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-staging
  template:
    metadata:
      labels:
        app: frontend-staging
    spec:
      containers:
        - name: frontend-staging
          image: irwan34/frontend-service:62617c0eae6fbbe6f7a5e509f1a708322683b3ff
          ports:
            - containerPort: 8080

