apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-api
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-api
  template:
    metadata:
      labels:
        app: myapp-api
    spec:
      containers:
        - name: myapp-api
          image: irwan34/api-service@sha256:dc0ba0fdeb47144c426e2a905050ba90d9ffb1c1b9c5b9b4004e23b59092cb38
          ports:
            - containerPort: 8000

