apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-api
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-api
  template:
    metadata:
      labels:
        app: myapp-api
    spec:
      containers:
        - name: myapp-api
          image: irwan34/api-service@sha256:0bc40d066640f0d3e4b36a55373fc3a984a69cb6111864c7de9c4ec21b789e90
          ports:
            - containerPort: 8000

