apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
        - name: myapp-frontend
          image: irwan34/frontend-service@sha256:1d822bf2c7fb47da94f21d3ccbb18050a38010396673dd5f13227f24102a5db3
          ports:
            - containerPort: 8000

