apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
        - name: myapp-frontend
          image: irwan34/frontend-service@sha256:936b9ac67cf07373f16b5ce2e6792e3cbfb373cad0cc0bb34bf6edd97c6b6fe7
          ports:
            - containerPort: 8000

