apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
        - name: myapp-frontend
          image: irwan34/frontend-service@sha256:85d446d0c9796f9c9ccc3a90359c77ec0244df31f658683e9c373e05c0641487
          ports:
            - containerPort: 8000

